# Monte Carlo Investment Calculator - Docker Compose Configuration

services:
  # Main web application
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/var/www/static:ro
    depends_on:
      - web
    restart: unless-stopped
    profiles:
      - production

  # Redis cache (optional, for future features)
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    profiles:
      - cache

volumes:
  logs:
    driver: local